import { defineStore } from 'pinia'
import { ref }         from 'vue'

export type Lang = 'uz' | 'ru' | 'en'

// ─────────────────────────────────────────────────────────────────────────────
// Tarjimalar
// ─────────────────────────────────────────────────────────────────────────────
const messages: Record<Lang, Record<string, string>> = {

  // ── O'ZBEK ──────────────────────────────────────────────────────────────
  uz: {
    // Navigatsiya
    'nav.home':          'Asosiy',
    'nav.recipes':       'Retseptlar',
    'nav.meal_plan':     'Haftalik reja',
    'nav.shopping':      'Xarid',
    'nav.admin':         'Admin',
    'nav.login':         'Kirish',
    'nav.register':      "Ro'yxat",
    'nav.logout':        'Chiqish',
    'nav.search':        'Qidirish...',
    'nav.search_mobile': 'Retsept qidirish...',
    'nav.profile':       'Profil',
    'nav.saved':         'Sevimlilar',
    'saved.count':       'ta saqlangan retsept',
    'saved.empty':       'Hali hech narsa saqlanmagan',

    // Umumiy
    'common.save':           'Saqlash',
    'common.cancel':         'Bekor qilish',
    'common.delete':         "O'chirish",
    'common.edit':           'Tahrirlash',
    'common.add':            "Qo'shish",
    'common.back':           'Orqaga',
    'common.loading':        'Yuklanmoqda...',
    'common.saving':         'Saqlanmoqda...',
    'common.easy':           'Oson',
    'common.medium':         "O'rta",
    'common.hard':           'Qiyin',
    'common.min':            'daq',
    'common.ppl':            'kishi',
    'common.total_time':     'Umumiy vaqt',
    'common.rating':         'Reyting',
    'common.views':          "Ko'rishlar",
    'common.servings':       'Porsiya',
    'common.visible':        "Ko'rinadi",
    'common.hidden':         'Yashirin',
    'common.all':            'Barchasi →',
    'common.confirm_delete': "O'chirishni tasdiqlaysizmi?",
    'common.error_delete':   "O'chirishda xatolik yuz berdi",
    'common.error_save':     'Saqlashda xatolik yuz berdi',

    // Bosh sahifa
    'home.badge':      "🌿 Sog'lom ovqatlanish",
    'home.title':      'Eng mazali retseptlar\nbir joyda!',
    'home.sub':        "O'zbek va jahon taomlarining eng yaxshi retseptlari.",
    'home.btn_browse': "Retseptlarni ko'rish",
    'home.btn_meal':   '📅 Haftalik reja',
    'home.stat_r':     'Retseptlar',
    'home.stat_c':     'Kategoriyalar',
    'home.stat_u':     'Foydalanuvchilar',
    'home.popular':    'Ommabop retseptlar',
    'home.categories': 'Kategoriyalar',
    'home.view_all':   'Barchasi →',
    'home.no_recipes': "Hozircha retsept yo'q",

    // Retseptlar sahifasi
    'recipes.title':          'Retseptlar',
    'recipes.search':         'Retsept qidirish...',
    'recipes.all_categories': 'Barcha kategoriya',
    'recipes.all_levels':     'Barcha daraja',
    'recipes.not_found':      'Retsept topilmadi',
    'recipes.not_found_sub':  "Boshqa kalit so'z yoki filtr sinab ko'ring",
    'recipes.reset':          'Filterni tozalash',
    'recipes.count':          'ta retsept',
    'recipes.add':            "Retsept qo'shish",
    'recipes.prev':           '← Oldingi',
    'recipes.next':           'Keyingi →',

    // Retsept detail
    'recipe.ingredients':    'Ingredientlar',
    'recipe.steps':          'Bosqichlar',
    'recipe.nutrition':      'Ozuqa',
    'recipe.no_ingredients': 'Ingredientlar kiritilmagan',
    'recipe.no_steps':       'Bosqichlar kiritilmagan',
    'recipe.no_nutrition':   "Ozuqaviy ma'lumot kiritilmagan",
    'recipe.author':         'Muallif',
    'recipe.edit':           'Tahrirlash',
    'recipe.delete':         "O'chirish",

    // Ozuqa
    'nutrition.calories': 'Kaloriya',
    'nutrition.protein':  'Oqsil',
    'nutrition.fat':      "Yog'",
    'nutrition.carbs':    'Uglevodlar',
    'nutrition.fiber':    'Kletchatka',
    'nutrition.sugar':    'Shakar',

    // Profil
    'profile.my_recipes':    'Mening retseptlarim',
    'profile.edit':          'Profilni tahrirlash',
    'profile.logout':        'Chiqish',
    'profile.no_recipes':    "Hali retsept qo'shmadingiz",
    'profile.no_recipes_sub':"Birinchi retseptingizni hoziroq yarating!",
    'profile.add_recipe':    "➕ Retsept qo'shish",
    'profile.full_name':     "To'liq ism",
    'profile.role':          'Rol',
    'profile.admin':         'Administrator',
    'profile.user':          'Foydalanuvchi',
    'profile.stat_recipes':  'Retseptlar',
    'profile.stat_saved':    'Saqlangan',
    'profile.stat_meal':     'Haftalik reja',
    'profile.save_profile':  'Saqlash',
    'profile.note':          "📌 Parolni o'zgartirish funksiyasi tez orada qo'shiladi",
    'profile.avatar_hint':   "Rasm o'zgartirish uchun bosing",
    'profile.pw_change':     "🔒 Parolni o'zgartirish",
    'profile.pw_current':    'Joriy parol',
    'profile.pw_new':        'Yangi parol',
    'profile.pw_confirm':    'Yangi parolni tasdiqlang',
    'profile.pw_save':       'Parolni saqlash',
    'profile.pw_saving':     'Saqlanmoqda...',
    'profile.pw_saved':      "✅ Parol muvaffaqiyatli o'zgartirildi!",
    'profile.pw_mismatch':   'Yangi parollar mos kelmadi',
    'profile.pw_short':      "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
    'profile.saved_ok':      '✅ Muvaffaqiyatli saqlandi!',
    'profile.name_ph':       'Ism familiya',
    'common.count':          'ta',

    // Auth
    'auth.login_title':    'Tizimga kirish',
    'auth.login_sub':      'Xush kelibsiz! Tizimga kiring.',
    'auth.register_title': 'Yangi hisob yaratish',
    'auth.register_sub':   "Chef tizimiga qo'shilish uchun ma'lumotlarni kiriting",
    'auth.username':       'Foydalanuvchi nomi',
    'auth.password':       'Parol',
    'auth.full_name':      "To'liq ism (ixtiyoriy)",
    'auth.email':          'Elektron pochta',
    'auth.login_btn':      'Kirish',
    'auth.register_btn':   "Ro'yxatdan o'tish",
    'auth.no_account':     "Hisob yo'qmi?",
    'auth.have_account':   'Hisob bormi?',
    'auth.register_link':  "Ro'yxatdan o'ting",
    'auth.login_link':     'Kiring',
    'auth.show_pass':      'Parolni ko\'rsatish',
    'auth.remember':       'Eslab qolish',
    'auth.forgot':         'Parolni unutdingizmi?',
    'auth.loading':        'Kirilmoqda...',
    'auth.registering':    "Ro'yxatdan o'tilmoqda...",

    // Admin
    'admin.title':         'Admin Panel',
    'admin.sub':           'OshPaz tizimini boshqaring',
    'admin.total_recipes': 'Jami retsept',
    'admin.categories':    'Kategoriya',
    'admin.easy_level':    'Oson daraja',
    'admin.hard_level':    'Qiyin daraja',
    'admin.search':        'Retsept qidirish...',
    'admin.add_recipe':    'Yangi retsept',
    'admin.recipe_list':   "Retseptlar ro'yxati",
    'admin.deleted':       "Retsept o'chirildi",
    'admin.delete_error':  "O'chirishda xatolik",

    // Forma
    'form.basic':            'Asosiy',
    'form.steps_tab':        'Bosqichlar',
    'form.ingredients_tab':  'Ingredientlar',
    'form.nutrition_tab':    'Ozuqa',
    'form.create_title':     "Yangi retsept qo'shish",
    'form.edit_title':       'Retseptni tahrirlash',
    'form.title_uz':         "Nomi (O'zbek) *",
    'form.title_ru':         'Nomi (Rus)',
    'form.description':      'Tavsif',
    'form.category':         'Kategoriya',
    'form.select_cat':       '— Kategoriya tanlang —',
    'form.difficulty':       'Qiyinlik darajasi',
    'form.prep_time':        'Tayyorgarlik (daq) *',
    'form.cook_time':        'Pishirish (daq) *',
    'form.servings':         'Porsiya *',
    'form.image':            'Rasm',
    'form.image_hint':       'Rasm tanlash uchun bosing',
    'form.image_sub':        'JPEG, PNG, WEBP · max 5MB',
    'form.image_change':     "🔄 O'zgartirish",
    'form.image_url':        "yoki URL ni qo'lda kiriting...",
    'form.visible':          "Ko'rinadigan qilish (published)",
    'form.video_url':        'Video URL',
    'form.step_instruction': 'Bosqich tavsifi...',
    'form.step_duration':    'Vaqt (daq, ixtiyoriy)',
    'form.step_image_url':   'Rasm URL (ixtiyoriy)',
    'form.add_step':         "Bosqich qo'shish",
    'form.ing_search':       'Ingredient qidirish...',
    'form.amount':           'Miqdor',
    'form.unit':             'Birlik',
    'form.add_ingredient':   "Ingredient qo'shish",
    'form.no_ingredients':   "Ingredient qo'shilmagan",
    'form.no_steps':         "Bosqich qo'shilmagan",
    'form.nutrition_enable': "Ozuqa ma'lumotini qo'shish",
    'form.calories':         'Kaloriya (kcal)',
    'form.protein':          'Oqsil (g)',
    'form.fat':              "Yog' (g)",
    'form.carbs':            'Uglevodlar (g)',
    'form.fiber':            'Kletchatka (g)',
    'form.sugar':            'Shakar (g)',
    'form.create_btn':       "Retsept qo'shish",
    'form.save_btn':         "O'zgarishlarni saqlash",
    'form.saving_btn':       'Saqlanmoqda...',
    'form.ing_searching':    'Qidirilmoqda...',
    'form.ing_not_found':    'Topilmadi',
    'form.notes':            'Izoh (ixtiyoriy)',

    // Xarid ro'yxati
    'shop.title':         "Xarid ro'yxati",
    'shop.sub':           "Haftalik rejadan avtomatik yarating",
    'shop.panel_title':   "Reja asosida avtomatik ro'yxat",
    'shop.panel_sub':     "Haftalik reja tanlang — barcha ingredientlar avtomatik qo'shiladi",
    'shop.select_plan':   "— Reja tanlang —",
    'shop.updating':      "Yangilanmoqda...",
    'shop.creating':      "Yaratilmoqda...",
    'shop.regenerate':    "Ro'yxatni yangilash",
    'shop.generate':      "Ro'yxat yaratish",
    'shop.need_plan':     "⚠️ Avval haftalik reja yarating",
    'shop.done_badge':    "✓ Tugallangan",
    'shop.items':         "mahsulot",
    'shop.empty_list':    "Ro'yxat bo'sh",
    'shop.empty_title':   "Hali ro'yxat yo'q",
    'shop.empty_sub':     "Yuqoridan reja tanlang va avtomatik ro'yxat yarating",
    'shop.confirm_del':   "Xarid ro'yxatini o'chirmoqchimisiz?",
    'shop.confirm_btn':   "Ha, o'chirish",
    'shop.refresh_title': "Reja o'zgardi — yangilash",
    'shop.created':       "Xarid ro'yxati yaratildi!",
    'shop.updated':       "Xarid ro'yxati yangilandi!",
    'shop.deleted':       "Ro'yxat o'chirildi!",
    'shop.error_create':  "Ro'yxat yaratishda xato",
    'shop.error_delete':  "O'chirishda xato",
    'shop.error_update':  "Yangilashda xato",

    // Admin kengaytirilgan
    'admin.tags':           'Teglar',
    'admin.ingredients':    'Ingredientlar',
    'admin.tab_recipes':    '🍽️ Retseptlar',
    'admin.tab_categories': '🏷️ Kategoriyalar',
    'admin.tab_tags':       '🔖 Teglar',
    'admin.tab_ingredients':'🥕 Ingredientlar',
    'admin.clear':          'Tozalash',
    'admin.cat_edit':       'Kategoriyani tahrirlash',
    'admin.cat_new':        'Yangi kategoriya',
    'admin.cat_color':      'Rang',
    'admin.cat_empty':      "Hali kategoriya yo'q",
    'admin.cat_saved':      "Kategoriya yangilandi!",
    'admin.cat_added':      "Kategoriya qo'shildi!",
    'admin.cat_deleted':    "Kategoriya o'chirildi!",
    'admin.tag_edit':       'Tegni tahrirlash',
    'admin.tag_new':        'Yangi teg',
    'admin.tag_empty':      "Hali teg yo'q",
    'admin.tag_saved':      "Teg yangilandi!",
    'admin.tag_added':      "Teg qo'shildi!",
    'admin.tag_deleted':    "Teg o'chirildi!",
    'admin.ing_search':     'Ingredient qidirish...',
    'admin.ing_add_btn':    "Ingredient qo'shish",
    'admin.ing_edit_title': 'Ingredientni tahrirlash',
    'admin.ing_add_title':  "Yangi ingredient qo'shish",
    'admin.ing_empty':      "Hali ingredient yo'q",
    'admin.ing_not_found':  'Natija topilmadi',
    'admin.ing_saved':      "Ingredient yangilandi!",
    'admin.ing_added':      "Ingredient qo'shildi!",
    'admin.ing_deleted':    "Ingredient o'chirildi!",
    'admin.allergen':       '⚠️ Allergik ingredient',
    'admin.ing_name_uz':    "Nom (O'zbek)",
    'admin.ing_name_ru':    'Nom (Rus)',
    'admin.ing_name_eng':   'Nom (Ingliz)',
    'admin.ing_image':      'Rasm',
    'admin.ing_unit':       "Standart o'lchov",
    'admin.ing_select_unit':'Tanlang',
    'admin.error':          'Xatolik',
    'admin.error_save':     'Saqlashda xatolik yuz berdi',
    'admin.prev':           '‹ Oldingi',
    'admin.next':           'Keyingi ›',
    'admin.result_n':       'ta',

    // Admin — Foydalanuvchilar
    'admin.tab_users':       '👥 Foydalanuvchilar',
    'admin.total_users':     'Foydalanuvchilar',
    'admin.user_search':     'Ism, email yoki username...',
    'admin.user_empty':      "Foydalanuvchilar yo'q",
    'admin.user_not_found':  'Foydalanuvchi topilmadi',
    'admin.user_block':      'Bloklash',
    'admin.user_unblock':    'Faollashtirish',
    'admin.user_block_ok':   '🚫 Foydalanuvchi bloklandi',
    'admin.user_unblock_ok': '✅ Foydalanuvchi faollashtirildi',
    'admin.user_active':     'Faol',
    'admin.user_blocked':    'Bloklangan',
    'admin.role_admin':      'Admin',
    'admin.role_user':       'Foydalanuvchi',
    'admin.user_edit':       'Tahrirlash',
    'admin.user_edit_title': 'Foydalanuvchini tahrirlash',
    'admin.user_fullname':   "To'liq ism",
    'admin.user_username':   'Username',
    'admin.user_email':      'Email',
    'admin.user_role':       'Rol',
    'admin.user_status':     'Status',
    'admin.user_saved':      '✅ Foydalanuvchi yangilandi!',
    'admin.user_save_err':   'Saqlashda xatolik yuz berdi',
    'admin.user_new_pw':     'Yangi parol (ixtiyoriy)',
    'admin.user_pw_hint':    "Bo'sh qoldirsa — parol o'zgarmaydi",
    'admin.user_pw_short':   "Parol kamida 4 ta belgidan iborat bo'lishi kerak",

    // Haftalik reja
    'meal.title':         'Haftalik reja',
    'meal.sub':           'Ovqat jadvalingizni rejalashtiring',
    'meal.new_plan':      'Yangi reja',
    'meal.new_plan_title':'Yangi haftalik reja',
    'meal.plan_name':     'Reja nomi',
    'meal.week_start':    'Hafta boshi (Dushanba)',
    'meal.notes':         'Izoh',
    'meal.optional':      '(ixtiyoriy)',
    'meal.creating':      'Yaratilmoqda...',
    'meal.create':        'Reja yaratish',
    'meal.activate':      'Faollashtirish',
    'meal.add_entry':     "Ovqat qo'shish",
    'meal.recipe':        'Retsept',
    'meal.day':           'Kun',
    'meal.meal_type':     'Ovqat vaqti',
    'meal.servings_lbl':  'Porsiya soni',
    'meal.adding':        "Qo'shilmoqda...",
    'meal.add':           "Qo'shish",
    'meal.no_plans':      "Hali reja yo'q",
    'meal.no_plans_sub':  'Yangi haftalik ovqat rejasi yarating',
    'meal.meals_count':   'ta ovqat',
    'meal.search_recipe': 'Retsept qidirish...',
    'meal.status_draft':  'Qoralama',
    'meal.status_active': 'Faol',
    'meal.status_done':   'Tugagan',
    'meal.days_short':    'Du,Se,Ch,Pa,Ju,Sh,Ya',
    'meal.days_full':     'Dushanba,Seshanba,Chorshanba,Payshanba,Juma,Shanba,Yakshanba',
    'meal.breakfast':     '🌅 Nonushta',
    'meal.lunch':         '☀️ Tushlik',
    'meal.dinner':        '🌙 Kechki',
    'meal.snack':         '🍎 Snack',
    'meal.edit_title':    'Rejani tahrirlash',
    'meal.edit_btn':      'Saqlash',
    'meal.load_entries':  'Yuklanmoqda...',
  },

  // ── РУССКИЙ ─────────────────────────────────────────────────────────────
  ru: {
    'nav.home':          'Главная',
    'nav.recipes':       'Рецепты',
    'nav.meal_plan':     'Недельный план',
    'nav.shopping':      'Покупки',
    'nav.admin':         'Админ',
    'nav.login':         'Войти',
    'nav.register':      'Регистрация',
    'nav.logout':        'Выйти',
    'nav.search':        'Поиск...',
    'nav.search_mobile': 'Поиск рецептов...',
    'nav.profile':       'Профиль',
    'nav.saved':         'Избранное',
    'saved.count':       'сохранённых рецептов',
    'saved.empty':       'Ничего не сохранено',

    'common.save':           'Сохранить',
    'common.cancel':         'Отмена',
    'common.delete':         'Удалить',
    'common.edit':           'Редактировать',
    'common.add':            'Добавить',
    'common.back':           'Назад',
    'common.loading':        'Загрузка...',
    'common.saving':         'Сохранение...',
    'common.easy':           'Простой',
    'common.medium':         'Средний',
    'common.hard':           'Сложный',
    'common.min':            'мин',
    'common.ppl':            'чел',
    'common.total_time':     'Общее время',
    'common.rating':         'Рейтинг',
    'common.views':          'Просмотры',
    'common.servings':       'Порций',
    'common.visible':        'Виден',
    'common.hidden':         'Скрыт',
    'common.all':            'Все →',
    'common.confirm_delete': 'Подтвердить удаление?',
    'common.error_delete':   'Ошибка при удалении',
    'common.error_save':     'Ошибка при сохранении',

    'home.badge':      '🌿 Здоровое питание',
    'home.title':      'Лучшие рецепты\nв одном месте!',
    'home.sub':        'Лучшие рецепты узбекской и мировой кухни.',
    'home.btn_browse': 'Смотреть рецепты',
    'home.btn_meal':   '📅 Недельный план',
    'home.stat_r':     'Рецепты',
    'home.stat_c':     'Категории',
    'home.stat_u':     'Пользователи',
    'home.popular':    'Популярные рецепты',
    'home.categories': 'Категории',
    'home.view_all':   'Все →',
    'home.no_recipes': 'Рецептов пока нет',

    'recipes.title':          'Рецепты',
    'recipes.search':         'Поиск рецептов...',
    'recipes.all_categories': 'Все категории',
    'recipes.all_levels':     'Все уровни',
    'recipes.not_found':      'Рецепт не найден',
    'recipes.not_found_sub':  'Попробуйте другое слово или фильтр',
    'recipes.reset':          'Сбросить фильтры',
    'recipes.count':          'рецептов',
    'recipes.add':            'Добавить рецепт',
    'recipes.prev':           '← Назад',
    'recipes.next':           'Вперёд →',

    'recipe.ingredients':    'Ингредиенты',
    'recipe.steps':          'Шаги',
    'recipe.nutrition':      'Питание',
    'recipe.no_ingredients': 'Ингредиенты не добавлены',
    'recipe.no_steps':       'Шаги не добавлены',
    'recipe.no_nutrition':   'Нет данных о питании',
    'recipe.author':         'Автор',
    'recipe.edit':           'Редактировать',
    'recipe.delete':         'Удалить',

    'nutrition.calories': 'Калории',
    'nutrition.protein':  'Белки',
    'nutrition.fat':      'Жиры',
    'nutrition.carbs':    'Углеводы',
    'nutrition.fiber':    'Клетчатка',
    'nutrition.sugar':    'Сахар',

    'profile.my_recipes':    'Мои рецепты',
    'profile.edit':          'Редактировать профиль',
    'profile.logout':        'Выйти',
    'profile.no_recipes':    'У вас нет рецептов',
    'profile.no_recipes_sub':'Создайте свой первый рецепт!',
    'profile.add_recipe':    '➕ Добавить рецепт',
    'profile.full_name':     'Полное имя',
    'profile.role':          'Роль',
    'profile.admin':         'Администратор',
    'profile.user':          'Пользователь',
    'profile.stat_recipes':  'Рецепты',
    'profile.stat_saved':    'Сохранённые',
    'profile.stat_meal':     'Недельный план',
    'profile.save_profile':  'Сохранить',
    'profile.note':          '📌 Смена пароля скоро будет доступна',
    'profile.avatar_hint':   'Нажмите для изменения фото',
    'profile.pw_change':     '🔒 Изменить пароль',
    'profile.pw_current':    'Текущий пароль',
    'profile.pw_new':        'Новый пароль',
    'profile.pw_confirm':    'Подтвердите новый пароль',
    'profile.pw_save':       'Сохранить пароль',
    'profile.pw_saving':     'Сохранение...',
    'profile.pw_saved':      '✅ Пароль успешно изменён!',
    'profile.pw_mismatch':   'Новые пароли не совпадают',
    'profile.pw_short':      'Пароль должен содержать не менее 6 символов',
    'profile.saved_ok':      '✅ Успешно сохранено!',
    'profile.name_ph':       'Имя Фамилия',
    'common.count':          'шт',

    'auth.login_title':    'Вход в систему',
    'auth.login_sub':      'Добро пожаловать! Войдите в систему.',
    'auth.register_title': 'Создать аккаунт',
    'auth.register_sub':   'Введите данные для регистрации',
    'auth.username':       'Имя пользователя',
    'auth.password':       'Пароль',
    'auth.full_name':      'Полное имя (необязательно)',
    'auth.email':          'Эл. почта',
    'auth.login_btn':      'Войти',
    'auth.register_btn':   'Зарегистрироваться',
    'auth.no_account':     'Нет аккаунта?',
    'auth.have_account':   'Уже есть аккаунт?',
    'auth.register_link':  'Зарегистрироваться',
    'auth.login_link':     'Войти',
    'auth.show_pass':      'Показать пароль',
    'auth.remember':       'Запомнить меня',
    'auth.forgot':         'Забыли пароль?',
    'auth.loading':        'Вход...',
    'auth.registering':    'Регистрация...',

    'admin.title':         'Панель администратора',
    'admin.sub':           'Управление системой OshPaz',
    'admin.total_recipes': 'Всего рецептов',
    'admin.categories':    'Категории',
    'admin.easy_level':    'Простой уровень',
    'admin.hard_level':    'Сложный уровень',
    'admin.search':        'Поиск рецептов...',
    'admin.add_recipe':    'Новый рецепт',
    'admin.recipe_list':   'Список рецептов',
    'admin.deleted':       'Рецепт удалён',
    'admin.delete_error':  'Ошибка при удалении',

    'form.basic':            'Основное',
    'form.steps_tab':        'Шаги',
    'form.ingredients_tab':  'Ингредиенты',
    'form.nutrition_tab':    'Питание',
    'form.create_title':     'Добавить рецепт',
    'form.edit_title':       'Редактировать рецепт',
    'form.title_uz':         'Название (Узб) *',
    'form.title_ru':         'Название (Рус)',
    'form.description':      'Описание',
    'form.category':         'Категория',
    'form.select_cat':       '— Выберите категорию —',
    'form.difficulty':       'Уровень сложности',
    'form.prep_time':        'Подготовка (мин) *',
    'form.cook_time':        'Приготовление (мин) *',
    'form.servings':         'Порций *',
    'form.image':            'Изображение',
    'form.image_hint':       'Нажмите для выбора изображения',
    'form.image_sub':        'JPEG, PNG, WEBP · макс 5МБ',
    'form.image_change':     '🔄 Изменить',
    'form.image_url':        'или введите URL вручную...',
    'form.visible':          'Опубликовать',
    'form.video_url':        'URL видео',
    'form.step_instruction': 'Описание шага...',
    'form.step_duration':    'Время (мин, необязательно)',
    'form.step_image_url':   'URL изображения (необязательно)',
    'form.add_step':         'Добавить шаг',
    'form.ing_search':       'Поиск ингредиента...',
    'form.amount':           'Количество',
    'form.unit':             'Единица',
    'form.add_ingredient':   'Добавить ингредиент',
    'form.no_ingredients':   'Ингредиенты не добавлены',
    'form.no_steps':         'Шаги не добавлены',
    'form.nutrition_enable': 'Добавить данные о питании',
    'form.calories':         'Калории (ккал)',
    'form.protein':          'Белки (г)',
    'form.fat':              'Жиры (г)',
    'form.carbs':            'Углеводы (г)',
    'form.fiber':            'Клетчатка (г)',
    'form.sugar':            'Сахар (г)',
    'form.create_btn':       'Добавить рецепт',
    'form.save_btn':         'Сохранить изменения',
    'form.saving_btn':       'Сохранение...',
    'form.ing_searching':    'Поиск...',
    'form.ing_not_found':    'Не найдено',
    'form.notes':            'Примечание (необязательно)',

    'shop.title':         'Список покупок',
    'shop.sub':           'Создайте автоматически из плана',
    'shop.panel_title':   'Автоматический список по плану',
    'shop.panel_sub':     'Выберите план — все ингредиенты добавятся автоматически',
    'shop.select_plan':   '— Выберите план —',
    'shop.updating':      'Обновление...',
    'shop.creating':      'Создание...',
    'shop.regenerate':    'Обновить список',
    'shop.generate':      'Создать список',
    'shop.need_plan':     '⚠️ Сначала создайте недельный план',
    'shop.done_badge':    '✓ Завершено',
    'shop.items':         'товаров',
    'shop.empty_list':    'Список пуст',
    'shop.empty_title':   'Нет списков',
    'shop.empty_sub':     'Выберите план выше и создайте список',
    'shop.confirm_del':   'Удалить список покупок?',
    'shop.confirm_btn':   'Да, удалить',
    'shop.refresh_title': 'План изменился — обновить',
    'shop.created':       'Список покупок создан!',
    'shop.updated':       'Список покупок обновлён!',
    'shop.deleted':       'Список удалён!',
    'shop.error_create':  'Ошибка создания списка',
    'shop.error_delete':  'Ошибка удаления',
    'shop.error_update':  'Ошибка обновления',

    'admin.tags':           'Теги',
    'admin.ingredients':    'Ингредиенты',
    'admin.tab_recipes':    '🍽️ Рецепты',
    'admin.tab_categories': '🏷️ Категории',
    'admin.tab_tags':       '🔖 Теги',
    'admin.tab_ingredients':'🥕 Ингредиенты',
    'admin.clear':          'Сбросить',
    'admin.cat_edit':       'Редактировать категорию',
    'admin.cat_new':        'Новая категория',
    'admin.cat_color':      'Цвет',
    'admin.cat_empty':      'Нет категорий',
    'admin.cat_saved':      'Категория обновлена!',
    'admin.cat_added':      'Категория добавлена!',
    'admin.cat_deleted':    'Категория удалена!',
    'admin.tag_edit':       'Редактировать тег',
    'admin.tag_new':        'Новый тег',
    'admin.tag_empty':      'Нет тегов',
    'admin.tag_saved':      'Тег обновлён!',
    'admin.tag_added':      'Тег добавлен!',
    'admin.tag_deleted':    'Тег удалён!',
    'admin.ing_search':     'Поиск ингредиентов...',
    'admin.ing_add_btn':    'Добавить ингредиент',
    'admin.ing_edit_title': 'Редактировать ингредиент',
    'admin.ing_add_title':  'Добавить новый ингредиент',
    'admin.ing_empty':      'Нет ингредиентов',
    'admin.ing_not_found':  'Ничего не найдено',
    'admin.ing_saved':      'Ингредиент обновлён!',
    'admin.ing_added':      'Ингредиент добавлен!',
    'admin.ing_deleted':    'Ингредиент удалён!',
    'admin.allergen':       '⚠️ Аллерген',
    'admin.ing_name_uz':    'Название (Узб)',
    'admin.ing_name_ru':    'Название (Рус)',
    'admin.ing_name_eng':   'Название (Англ)',
    'admin.ing_image':      'Изображение',
    'admin.ing_unit':       'Стандартная единица',
    'admin.ing_select_unit':'Выберите',
    'admin.error':          'Ошибка',
    'admin.error_save':     'Ошибка при сохранении',
    'admin.prev':           '‹ Назад',
    'admin.next':           'Вперёд ›',
    'admin.result_n':       'шт',

    // Admin — Пользователи
    'admin.tab_users':       '👥 Пользователи',
    'admin.total_users':     'Пользователи',
    'admin.user_search':     'Имя, email или username...',
    'admin.user_empty':      'Нет пользователей',
    'admin.user_not_found':  'Пользователь не найден',
    'admin.user_block':      'Заблокировать',
    'admin.user_unblock':    'Активировать',
    'admin.user_block_ok':   '🚫 Пользователь заблокирован',
    'admin.user_unblock_ok': '✅ Пользователь активирован',
    'admin.user_active':     'Активен',
    'admin.user_blocked':    'Заблокирован',
    'admin.role_admin':      'Админ',
    'admin.role_user':       'Пользователь',
    'admin.user_edit':       'Редактировать',
    'admin.user_edit_title': 'Редактировать пользователя',
    'admin.user_fullname':   'Полное имя',
    'admin.user_username':   'Username',
    'admin.user_email':      'Email',
    'admin.user_role':       'Роль',
    'admin.user_status':     'Статус',
    'admin.user_saved':      '✅ Пользователь обновлён!',
    'admin.user_save_err':   'Ошибка при сохранении',
    'admin.user_new_pw':     'Новый пароль (необязательно)',
    'admin.user_pw_hint':    'Оставьте пустым — пароль не изменится',
    'admin.user_pw_short':   'Пароль должен содержать не менее 4 символов',

    'meal.title':         'Недельный план',
    'meal.sub':           'Планируйте своё питание',
    'meal.new_plan':      'Новый план',
    'meal.new_plan_title':'Новый недельный план',
    'meal.plan_name':     'Название плана',
    'meal.week_start':    'Начало недели (Понедельник)',
    'meal.notes':         'Заметки',
    'meal.optional':      '(необязательно)',
    'meal.creating':      'Создание...',
    'meal.create':        'Создать план',
    'meal.activate':      'Активировать',
    'meal.draft_hint':    'План ещё в черновике — нажмите, чтобы активировать',
    'meal.add_entry':     'Добавить блюдо',
    'meal.recipe':        'Рецепт',
    'meal.day':           'День',
    'meal.meal_type':     'Тип питания',
    'meal.servings_lbl':  'Количество порций',
    'meal.adding':        'Добавление...',
    'meal.add':           'Добавить',
    'meal.no_plans':      'Нет планов',
    'meal.no_plans_sub':  'Создайте новый недельный план питания',
    'meal.meals_count':   'блюд',
    'meal.search_recipe': 'Поиск рецептов...',
    'meal.status_draft':  'Черновик',
    'meal.status_active': 'Активный',
    'meal.status_done':   'Завершён',
    'meal.days_short':    'Пн,Вт,Ср,Чт,Пт,Сб,Вс',
    'meal.days_full':     'Понедельник,Вторник,Среда,Четверг,Пятница,Суббота,Воскресенье',
    'meal.breakfast':     '🌅 Завтрак',
    'meal.lunch':         '☀️ Обед',
    'meal.dinner':        '🌙 Ужин',
    'meal.snack':         '🍎 Перекус',
    'meal.edit_title':    'Редактировать план',
    'meal.edit_btn':      'Сохранить',
    'meal.load_entries':  'Загрузка...',
  },

  // ── ENGLISH ──────────────────────────────────────────────────────────────
  en: {
    'nav.home':          'Home',
    'nav.recipes':       'Recipes',
    'nav.meal_plan':     'Meal Plan',
    'nav.shopping':      'Shopping',
    'nav.admin':         'Admin',
    'nav.login':         'Login',
    'nav.register':      'Register',
    'nav.logout':        'Logout',
    'nav.search':        'Search...',
    'nav.search_mobile': 'Search recipes...',
    'nav.profile':       'Profile',
    'nav.saved':         'Favorites',
    'saved.count':       'saved recipes',
    'saved.empty':       'Nothing saved yet',

    'common.save':           'Save',
    'common.cancel':         'Cancel',
    'common.delete':         'Delete',
    'common.edit':           'Edit',
    'common.add':            'Add',
    'common.back':           'Back',
    'common.loading':        'Loading...',
    'common.saving':         'Saving...',
    'common.easy':           'Easy',
    'common.medium':         'Medium',
    'common.hard':           'Hard',
    'common.min':            'min',
    'common.ppl':            'ppl',
    'common.total_time':     'Total time',
    'common.rating':         'Rating',
    'common.views':          'Views',
    'common.servings':       'Servings',
    'common.visible':        'Visible',
    'common.hidden':         'Hidden',
    'common.all':            'All →',
    'common.confirm_delete': 'Confirm delete?',
    'common.error_delete':   'Error deleting',
    'common.error_save':     'Error saving',

    'home.badge':      '🌿 Healthy eating',
    'home.title':      'Best recipes\nin one place!',
    'home.sub':        'The best recipes of Uzbek and world cuisine.',
    'home.btn_browse': 'Browse Recipes',
    'home.btn_meal':   '📅 Meal Plan',
    'home.stat_r':     'Recipes',
    'home.stat_c':     'Categories',
    'home.stat_u':     'Users',
    'home.popular':    'Popular Recipes',
    'home.categories': 'Categories',
    'home.view_all':   'All →',
    'home.no_recipes': 'No recipes yet',

    'recipes.title':          'Recipes',
    'recipes.search':         'Search recipes...',
    'recipes.all_categories': 'All categories',
    'recipes.all_levels':     'All levels',
    'recipes.not_found':      'No recipes found',
    'recipes.not_found_sub':  'Try a different keyword or filter',
    'recipes.reset':          'Reset filters',
    'recipes.count':          'recipes',
    'recipes.add':            'Add recipe',
    'recipes.prev':           '← Previous',
    'recipes.next':           'Next →',

    'recipe.ingredients':    'Ingredients',
    'recipe.steps':          'Steps',
    'recipe.nutrition':      'Nutrition',
    'recipe.no_ingredients': 'No ingredients added',
    'recipe.no_steps':       'No steps added',
    'recipe.no_nutrition':   'No nutritional information',
    'recipe.author':         'Author',
    'recipe.edit':           'Edit',
    'recipe.delete':         'Delete',

    'nutrition.calories': 'Calories',
    'nutrition.protein':  'Protein',
    'nutrition.fat':      'Fat',
    'nutrition.carbs':    'Carbs',
    'nutrition.fiber':    'Fiber',
    'nutrition.sugar':    'Sugar',

    'profile.my_recipes':    'My Recipes',
    'profile.edit':          'Edit Profile',
    'profile.logout':        'Logout',
    'profile.no_recipes':    'No recipes yet',
    'profile.no_recipes_sub':'Create your first recipe now!',
    'profile.add_recipe':    '➕ Add Recipe',
    'profile.full_name':     'Full Name',
    'profile.role':          'Role',
    'profile.admin':         'Administrator',
    'profile.user':          'User',
    'profile.stat_recipes':  'Recipes',
    'profile.stat_saved':    'Saved',
    'profile.stat_meal':     'Meal Plan',
    'profile.save_profile':  'Save',
    'profile.note':          '📌 Password change coming soon',
    'profile.avatar_hint':   'Click to change photo',
    'profile.pw_change':     '🔒 Change Password',
    'profile.pw_current':    'Current password',
    'profile.pw_new':        'New password',
    'profile.pw_confirm':    'Confirm new password',
    'profile.pw_save':       'Save password',
    'profile.pw_saving':     'Saving...',
    'profile.pw_saved':      '✅ Password changed successfully!',
    'profile.pw_mismatch':   'New passwords do not match',
    'profile.pw_short':      'Password must be at least 6 characters',
    'profile.saved_ok':      '✅ Saved successfully!',
    'profile.name_ph':       'Full name',
    'common.count':          '',

    'auth.login_title':    'Sign In',
    'auth.login_sub':      'Welcome! Sign in to your account.',
    'auth.register_title': 'Create Account',
    'auth.register_sub':   'Enter your details to register',
    'auth.username':       'Username',
    'auth.password':       'Password',
    'auth.full_name':      'Full Name (optional)',
    'auth.email':          'Email',
    'auth.login_btn':      'Sign In',
    'auth.register_btn':   'Sign Up',
    'auth.no_account':     'No account?',
    'auth.have_account':   'Already have account?',
    'auth.register_link':  'Register',
    'auth.login_link':     'Login',
    'auth.show_pass':      'Show password',
    'auth.remember':       'Remember me',
    'auth.forgot':         'Forgot password?',
    'auth.loading':        'Signing in...',
    'auth.registering':    'Registering...',

    'admin.title':         'Admin Panel',
    'admin.sub':           'Manage OshPaz system',
    'admin.total_recipes': 'Total recipes',
    'admin.categories':    'Categories',
    'admin.easy_level':    'Easy level',
    'admin.hard_level':    'Hard level',
    'admin.search':        'Search recipes...',
    'admin.add_recipe':    'New recipe',
    'admin.recipe_list':   'Recipe list',
    'admin.deleted':       'Recipe deleted',
    'admin.delete_error':  'Error deleting',

    'form.basic':            'Basic',
    'form.steps_tab':        'Steps',
    'form.ingredients_tab':  'Ingredients',
    'form.nutrition_tab':    'Nutrition',
    'form.create_title':     'Create Recipe',
    'form.edit_title':       'Edit Recipe',
    'form.title_uz':         'Name (Uzbek) *',
    'form.title_ru':         'Name (Russian)',
    'form.description':      'Description',
    'form.category':         'Category',
    'form.select_cat':       '— Select category —',
    'form.difficulty':       'Difficulty',
    'form.prep_time':        'Prep time (min) *',
    'form.cook_time':        'Cook time (min) *',
    'form.servings':         'Servings *',
    'form.image':            'Image',
    'form.image_hint':       'Click to select image',
    'form.image_sub':        'JPEG, PNG, WEBP · max 5MB',
    'form.image_change':     '🔄 Change',
    'form.image_url':        'or enter URL manually...',
    'form.visible':          'Publish recipe',
    'form.video_url':        'Video URL',
    'form.step_instruction': 'Step description...',
    'form.step_duration':    'Duration (min, optional)',
    'form.step_image_url':   'Image URL (optional)',
    'form.add_step':         'Add step',
    'form.ing_search':       'Search ingredient...',
    'form.amount':           'Amount',
    'form.unit':             'Unit',
    'form.add_ingredient':   'Add ingredient',
    'form.no_ingredients':   'No ingredients added',
    'form.no_steps':         'No steps added',
    'form.nutrition_enable': 'Add nutritional info',
    'form.calories':         'Calories (kcal)',
    'form.protein':          'Protein (g)',
    'form.fat':              'Fat (g)',
    'form.carbs':            'Carbohydrates (g)',
    'form.fiber':            'Fiber (g)',
    'form.sugar':            'Sugar (g)',
    'form.create_btn':       'Create Recipe',
    'form.save_btn':         'Save Changes',
    'form.saving_btn':       'Saving...',
    'form.ing_searching':    'Searching...',
    'form.ing_not_found':    'Not found',
    'form.notes':            'Notes (optional)',

    'shop.title':         'Shopping List',
    'shop.sub':           'Generate automatically from meal plan',
    'shop.panel_title':   'Auto list from meal plan',
    'shop.panel_sub':     'Select a plan — all ingredients will be added automatically',
    'shop.select_plan':   '— Select Plan —',
    'shop.updating':      'Updating...',
    'shop.creating':      'Creating...',
    'shop.regenerate':    'Regenerate list',
    'shop.generate':      'Generate list',
    'shop.need_plan':     '⚠️ Create a meal plan first',
    'shop.done_badge':    '✓ Done',
    'shop.items':         'items',
    'shop.empty_list':    'List is empty',
    'shop.empty_title':   'No lists yet',
    'shop.empty_sub':     'Select a plan above to generate a shopping list',
    'shop.confirm_del':   'Delete this shopping list?',
    'shop.confirm_btn':   'Yes, delete',
    'shop.refresh_title': 'Plan changed — refresh',
    'shop.created':       'Shopping list created!',
    'shop.updated':       'Shopping list updated!',
    'shop.deleted':       'List deleted!',
    'shop.error_create':  'Error creating list',
    'shop.error_delete':  'Error deleting',
    'shop.error_update':  'Error updating',

    'admin.tags':           'Tags',
    'admin.ingredients':    'Ingredients',
    'admin.tab_recipes':    '🍽️ Recipes',
    'admin.tab_categories': '🏷️ Categories',
    'admin.tab_tags':       '🔖 Tags',
    'admin.tab_ingredients':'🥕 Ingredients',
    'admin.clear':          'Clear',
    'admin.cat_edit':       'Edit Category',
    'admin.cat_new':        'New Category',
    'admin.cat_color':      'Color',
    'admin.cat_empty':      'No categories yet',
    'admin.cat_saved':      'Category updated!',
    'admin.cat_added':      'Category added!',
    'admin.cat_deleted':    'Category deleted!',
    'admin.tag_edit':       'Edit Tag',
    'admin.tag_new':        'New Tag',
    'admin.tag_empty':      'No tags yet',
    'admin.tag_saved':      'Tag updated!',
    'admin.tag_added':      'Tag added!',
    'admin.tag_deleted':    'Tag deleted!',
    'admin.ing_search':     'Search ingredients...',
    'admin.ing_add_btn':    'Add ingredient',
    'admin.ing_edit_title': 'Edit Ingredient',
    'admin.ing_add_title':  'Add New Ingredient',
    'admin.ing_empty':      'No ingredients yet',
    'admin.ing_not_found':  'No results found',
    'admin.ing_saved':      'Ingredient updated!',
    'admin.ing_added':      'Ingredient added!',
    'admin.ing_deleted':    'Ingredient deleted!',
    'admin.allergen':       '⚠️ Allergen',
    'admin.ing_name_uz':    'Name (Uzbek)',
    'admin.ing_name_ru':    'Name (Russian)',
    'admin.ing_name_eng':   'Name (English)',
    'admin.ing_image':      'Image',
    'admin.ing_unit':       'Default unit',
    'admin.ing_select_unit':'Select',
    'admin.error':          'Error',
    'admin.error_save':     'Error saving',
    'admin.prev':           '‹ Previous',
    'admin.next':           'Next ›',
    'admin.result_n':       '',

    // Admin — Users
    'admin.tab_users':       '👥 Users',
    'admin.total_users':     'Users',
    'admin.user_search':     'Name, email or username...',
    'admin.user_empty':      'No users found',
    'admin.user_not_found':  'User not found',
    'admin.user_block':      'Block',
    'admin.user_unblock':    'Activate',
    'admin.user_block_ok':   '🚫 User blocked',
    'admin.user_unblock_ok': '✅ User activated',
    'admin.user_active':     'Active',
    'admin.user_blocked':    'Blocked',
    'admin.role_admin':      'Admin',
    'admin.role_user':       'User',
    'admin.user_edit':       'Edit',
    'admin.user_edit_title': 'Edit user',
    'admin.user_fullname':   'Full name',
    'admin.user_username':   'Username',
    'admin.user_email':      'Email',
    'admin.user_role':       'Role',
    'admin.user_status':     'Status',
    'admin.user_saved':      '✅ User updated!',
    'admin.user_save_err':   'Error saving user',
    'admin.user_new_pw':     'New password (optional)',
    'admin.user_pw_hint':    'Leave blank — password stays unchanged',
    'admin.user_pw_short':   'Password must be at least 4 characters',

    'meal.title':         'Meal Plan',
    'meal.sub':           'Plan your weekly meals',
    'meal.new_plan':      'New Plan',
    'meal.new_plan_title':'New Weekly Plan',
    'meal.plan_name':     'Plan name',
    'meal.week_start':    'Week Start (Monday)',
    'meal.notes':         'Notes',
    'meal.optional':      '(optional)',
    'meal.creating':      'Creating...',
    'meal.create':        'Create Plan',
    'meal.activate':      'Activate',
    'meal.draft_hint':    'Plan is still a draft — click to activate',
    'meal.add_entry':     'Add Meal',
    'meal.recipe':        'Recipe',
    'meal.day':           'Day',
    'meal.meal_type':     'Meal Type',
    'meal.servings_lbl':  'Servings',
    'meal.adding':        'Adding...',
    'meal.add':           'Add',
    'meal.no_plans':      'No plans yet',
    'meal.no_plans_sub':  'Create a new weekly meal plan',
    'meal.meals_count':   'meals',
    'meal.search_recipe': 'Search recipes...',
    'meal.status_draft':  'Draft',
    'meal.status_active': 'Active',
    'meal.status_done':   'Completed',
    'meal.days_short':    'Mo,Tu,We,Th,Fr,Sa,Su',
    'meal.days_full':     'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
    'meal.breakfast':     '🌅 Breakfast',
    'meal.lunch':         '☀️ Lunch',
    'meal.dinner':        '🌙 Dinner',
    'meal.snack':         '🍎 Snack',
    'meal.edit_title':    'Edit Plan',
    'meal.edit_btn':      'Save',
    'meal.load_entries':  'Loading...',
  },
}

// ─────────────────────────────────────────────────────────────────────────────
// Pinia Store
// ─────────────────────────────────────────────────────────────────────────────
const LANG_KEY = 'oshpaz_lang'

export const useLangStore = defineStore('lang', () => {
  const lang = ref<Lang>((localStorage.getItem(LANG_KEY) as Lang) || 'uz')

  /** Tarjima qilish */
  function t(key: string): string {
    return messages[lang.value]?.[key] ?? messages.uz?.[key] ?? key
  }

  /** Tilni o'zgartirish */
  function setLang(l: Lang) {
    lang.value = l
    localStorage.setItem(LANG_KEY, l)
  }

  // ── Recipe matn yordamchilari ──────────────────────────────────────────

  /** Retsept sarlavhasi — tanlangan tilga qarab */
  function recipeTitle(r: any): string {
    if (!r) return ''
    if (lang.value === 'ru' && r.titleRu)  return r.titleRu
    if (lang.value === 'en' && r.titleEng) return r.titleEng
    return r.titleUz || r.titleRu || r.titleEng || ''
  }

  /** Ingredient nomi — tanlangan tilga qarab
   *  RecipeIngredientDto: ingredientNameUz / ingredientNameRu / ingredientNameEng
   *  IngredientDto (search): nameUz / nameRu / nameEng
   */
  function ingName(ing: any): string {
    if (!ing) return ''
    const uz  = ing.ingredientNameUz  ?? ing.nameUz  ?? ''
    const ru  = ing.ingredientNameRu  ?? ing.nameRu  ?? ''
    const en  = ing.ingredientNameEng ?? ing.nameEng ?? ''
    if (lang.value === 'ru' && ru)  return ru
    if (lang.value === 'en' && en)  return en
    return uz || ru || en || ''
  }

  /** Kategoriya nomi — tanlangan tilga qarab
   *  CategoryDto: nameUz / nameRu / nameEng
   *  RecipeDto ichida: categoryNameUz / categoryNameRu / categoryNameEng
   */
  function catName(c: any): string {
    if (!c) return ''
    const uz  = c.nameUz  ?? c.categoryNameUz  ?? ''
    const ru  = c.nameRu  ?? c.categoryNameRu  ?? ''
    const en  = c.nameEng ?? c.categoryNameEng ?? ''
    if (lang.value === 'ru' && ru) return ru
    if (lang.value === 'en' && en) return en
    return uz || ru || en || ''
  }

  return { lang, t, setLang, recipeTitle, ingName, catName }
})
